### ISSUE TITLE
Update starknetkit demo to the latest version of starknetkit

### ISSUE THREAD

**Issue by fracek** [apibara/starknet-react#483] opened 2024-08-21 17:12 UTC
We have a demo that uses starknetkit that needs to be updated to the latest release of starknetkit. We should also test that the demo works with the latest release.

edit: please ensure that you install latest version of `starknetkit` with tag `next`, `pnpm add starknetkit@next`

**Comment by kateberryd** [comment] 2024-08-21 17:12
Hi

**Comment by Gift-Naomi** [comment] 2024-08-21 17:13
Hi

**Comment by ShantelPeters** [comment] 2024-08-21 17:53
Please can I on work on this ?

**Comment by martinvibes** [comment] 2024-08-21 18:55
hello @fracek i would love to participate on this issue

**Comment by Blumebee** [comment] 2024-08-21 19:55
Hi @kateberryd @Oshioke-Salaki @martinvibes @Gift-Naomi @ShantelPeters , all applications must go through the ODHack hackathon page. All information are in the main telegram group or here: https://app.onlydust.com/hackathons/odhack-70 

Maintainers will be reviewing applications via the platform, not through the comments. Thanks for understanding and respecting this way!

**Comment by Supa-mega** [comment] 2024-08-22 00:12
@fracek can i pls work on this ?

**Comment by Gift-Naomi** [comment] 2024-08-22 04:46
@Blumebee The issue doesn't appear in onlydust

**Comment by Zeegaths** [comment] 2024-08-22 07:40
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
I have experience with starknetkit and good reserch skills.

### How I plan on tackling this issue
Check the lateste release, see where the version is set, update , test

**Comment by lindsaymoralesb** [comment] 2024-08-22 07:47
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
Hi! My name is Lindsay, and I'm a Software Engineer based in Costa Rica. I'm part of Dojo Coding and thanks to that I've already successfully contributed to 4 ODHacks in various projects, feel free to check my profile and contributions.
I've been working over the past 4.5 years as a full stack developer, specializing myself in frontend development. I've successfully integrated APis, developed new features, optmize projects, improving responsiveness, etc with the most known/used FE frameworks such as React, Next, Vue, and Angular. All this experience plus some courses I've taken had helped me master both javascript and typescript languages.

### How I plan on tackling this issue
First I’ll start by setting up and get the demo project running.
Then, I’ll check the kit version it is using and start the upgrade to the latest version. And made any needed changes.
Finally I’ll test the app throughly to make sure it keeps working as before.

**Comment by Dprof-in-tech** [comment] 2024-08-22 07:49
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
As an experienced Full Stack Blockchain Developer, I'm excited to contribute my expertise to Edition 7 of the OnlyDust hackathons. With a strong background in Next.js, TypeScript, JavaScript, React, Node.js, Solidity, and Cairo, I've honed my technical skills across the blockchain development landscape.
My journey with OnlyDust began at Edition 2, and I've since made 28 contributions across 11 projects. This extensive experience on the platform has allowed me to develop a keen understanding of delivering high-quality solutions under tight deadlines. I bring a unique blend of technical prowess and user-centric design to every project, whether I'm crafting immersive 3D experiences or developing innovative smart contracts.
My track record demonstrates my ability to adapt quickly and contribute effectively to diverse challenges. I'm confident in my capacity to tackle new problems and drive innovation in the blockchain space. As we embark on Edition 7, I'm eager to leverage my hackathon experience and technical skills to push the boundaries of what's possible in blockchain development.
With a passion for creating cutting-edge solutions, I'm excited to collaborate with the OnlyDust community and contribute to the advancement of the blockchain ecosystem.


### How I plan on tackling this issue
To solve it, i would:

Update Starknetkit Dependencies
Review the current version of Starknetkit used in the demo.
Update the package.json file to use the latest stable release of Starknetkit.
Run npm update or yarn upgrade to update all related dependencies.
Code Refactoring
Review the demo codebase and identify areas that need to be updated due to API changes in the latest Starknetkit release.
Refactor the code to align with any new patterns or best practices introduced in the latest version.
Update any deprecated method calls or components.
Testing
Set up a test environment that mirrors the production setup.
Perform comprehensive testing of all features in the demo:
Wallet connection
Transaction signing
Contract interactions
Any other Starknetkit-specific functionalities
Test across different browsers and devices to ensure compatibility.
Document any issues or unexpected behaviors encountered during testing.
Bug Fixes and Optimizations
Address any bugs or issues found during the testing phase.
Implement any necessary optimizations to improve performance or user experience.
Documentation Update
Update the demo's README file to reflect the new Starknetkit version and any changes in setup or usage.
Update any inline comments in the code to reflect changes made.
Cross-compatibility Check
Ensure the demo works with different Starknet wallets (e.g., ArgentX, Braavos).
Verify compatibility with both Starknet mainnet and testnet.

**Comment by kateberryd** [comment] 2024-08-22 07:58
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
Please can I be assign this issue

### How I plan on tackling this issue
I'm an familiar with starknet@latest and starknet@next updates

**Comment by Ugo-X** [comment] 2024-08-22 08:11
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, and Solidity. My journey with OnlyDust hackathons began at Edition 1, and I've since made 47 contributions across 11 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure.
I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges.
As we surf through Edition 7, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.


### How I plan on tackling this issue
I will approach the task of updating the demo that uses starknetkit to the latest release and testing its functionality as follows:

1. **Review current demo and starknetkit version**:
   a. I will examine the existing demo to understand its structure and how it currently uses starknetkit.
   b. I will identify the current version of starknetkit being used in the demo.

2. **Update starknetkit dependency**:
   a. I will update the package.json file to specify the latest stable version of starknetkit.
   b. I will run the package manager's update command (npm update or yarn upgrade) to install the latest version.

3. **Refactor demo code**:
   a. I will review the changelog or release notes of starknetkit to identify any breaking changes or new features.
   b. I will update the demo code to accommodate any API changes in the latest starknetkit release.
   c. I will implement any new features or best practices introduced in the latest version, if applicable.

4. **Update development environment**:
   a. I will ensure that all related dependencies are compatible with the new starknetkit version.
   b. I will update any development tools or configurations if necessary.

5. **Test functionality**:
   a. I will run the demo locally to verify that it starts without errors.
   b. I will test all existing features of the demo to ensure they still work as expected with the new starknetkit version.
   c. I will pay special attention to wallet connection, transaction signing, and any Starknet-specific functionality.

6. **Implement additional tests**:
   a. I will create new test cases to cover any new features or changes introduced in the latest starknetkit release.
   b. I will ensure that error handling and edge cases are properly tested.

7. **Documentation updates**:
   a. I will update any documentation within the demo project to reflect the new starknetkit version and any changes in usage.
   b. I will add notes about the update process and any significant changes to the README file.

8. **Performance check**:
   a. I will compare the performance of the demo with the new starknetkit version against the previous version.
   b. I will identify and address any performance regressions, if found.

9. **Cross-browser and cross-device testing**:
   a. I will test the updated demo across multiple browsers to ensure compatibility.
   b. I will verify that the demo works correctly on both desktop and mobile devices.

10. **Final review and submission**:
    a. I will conduct a final code review to ensure all changes are correct and follow best practices.
    b. I will create a pull request with a detailed description of the updates made and the test results.
    c. I will be prepared to address any feedback or questions from the review process.

By following these steps, I will ensure that the demo is successfully updated to use the latest release of starknetkit and that it functions correctly with the new version. This approach covers not only the update process but also thorough testing and documentation to maintain the demo's quality and usefulness.

**Comment by Otaiki1** [comment] 2024-08-22 08:16
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
Hi there 
I’m a frontend developer skilled in TypeScript and ReactJS with years of experience 


### How I plan on tackling this issue

With a strong grasp of the latest updates in Starknetkit, including changes between starknet@next and starknet@latest, I will go through all the import statements and update it, also check for errors to ensure compattibility.

**Comment by martinvibes** [comment] 2024-08-22 08:52
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
i'm a frontend dev and i have skills in react, typescript, next.js, tailwind, sass, boostrap etc. i would love to work on this i i'm giving the oppotunity


### How I plan on tackling this issue
Identify Current Version: Check the package.json file for the installed StarknetKit version.
Update StarknetKit: Use npm update or yarn upgrade to update to the latest version.
Verify Installation: Ensure the version has been updated correctly.
Test the Demo: Run the demo and thoroughly test all functionalities.
Address Issues: If you encounter issues, investigate and make necessary adjustments.
Retest: Retest the demo to ensure it's working as expected with the latest StarknetKit version.

**Comment by josephchimebuka** [comment] 2024-08-22 08:53
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
Hello Group lead I am Joseph Chimebuka I'm a full-stack software developer with 4+ years of experience in crafting innovative products. I've built a range of projects, including https://mattedsgn.vercel.app/ and https://metacrypt.vercel.app/ showcasing my expertise in React, Next.js, and blockchain technologies. I'm also an active contributor onlydust. here's my account https://app.onlydust.com/u/josephchimebuka.

### How I plan on tackling this issue
I'll look up the latest version of StarknetKit in its official repository or documentation to ensure I'm updating to the most recent release.
 I'll update the StarknetKit dependency in my project's package.json file to the latest version. This can typically be done by running a command like npm install starknetkit@latest or yarn add starknetkit@latest.I'll make any necessary changes to my code to accommodate updates or new features introduced in the latest version of StarknetKit.

**Comment by ScottyDavies** [comment] 2024-08-22 13:12
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
I have extensive experience in front-end and full-stack web development, working with a variety of frameworks and libraries, including React, Vue.js, and various state management solutions. I'm particularly adept at integrating third-party libraries and APIs into web applications

### How I plan on tackling this issue
I would approach this issue with following steps
Set up the environment:
Install the latest starknetkit version using pnpm add starknetkit@next.
Set up the demo application's codebase.
Understand the codebase:
Review the code and identify areas using starknetkit.
Update the codebase:
Migrate to the latest starknetkit API, addressing any breaking changes.
Test the updated code locally.
Implement testing:
Create a comprehensive test suite covering the application's key functionality.
Run tests to ensure no regressions.
Optimize the application:
Refactor and optimize the codebase for performance, maintainability, and responsiveness.
Document the changes:
Update the project's documentation with instructions for setup, running, and testing.
Prepare for future updates:
Set up a process for monitoring starknetkit releases and updating the demo accordingly.
Implement CI/CD to streamline the update process.

**Comment by ShantelPeters** [comment] 2024-08-22 13:28
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
To update the demo with the latest release of `starknetkit`:

1. **Upgrade Package:** Install the latest version of `starknetkit` using `pnpm add starknetkit@next`.
2. **Update Demo:** Refactor the demo code to be compatible with any breaking changes or new features in the latest release.
3. **Test Functionality:** Ensure the demo works as expected with the updated `starknetkit`, verifying all features and interactions.

### How I plan on tackling this issue
1. **Install Latest Version:** Run `pnpm add starknetkit@next` to update to the latest release.
2. **Update Demo:** Modify the demo code to be compatible with changes in the new version.
3. **Test Thoroughly:** Verify that the demo functions correctly with the updated `starknetkit`, checking for any issues or regressions.

**Comment by lindsaymoralesb** [comment] 2024-08-22 17:37
Thank you @fracek will start right away and let you know if I encounter any issues

**Comment by lindsaymoralesb** [comment] 2024-08-23 15:01
Hi @fracek just opened the PR. Please read the solution description I wrote there to make sure the issue was approached correctly.

**Closed** 2024-08-25 17:27 UTC
Labels: ODHack7, good-first-issue
