### ISSUE TITLE
bug: address & connector from useAccount are undefined

### ISSUE THREAD

**Issue by irisdv** [apibara/starknet-react#466] opened 2024-07-15 10:06 UTC
When I test our connection button with v3 of starknet-react, the value of `account` from `useAccount` is defined correctly, `isConnected` is `true`,  but `address` is `undefined` and `connector` is `undefined`.

Here is how I connect : 

```
import { InjectedConnector } from "starknetkit/injected";
import { Connector } from "@starknet-react/core";

 const connectors = [
    new InjectedConnector({ options: { id: "argentX" } }),
    new InjectedConnector({ options: { id: "braavos" } }),
  ];
 <StarknetConfig
              chains={chains}
              provider={providers}
              connectors={connectors as Connector[]}
              autoConnect
            ></StarknetConfig>
```
 
```
import { Connector, useConnect } from "@starknet-react/core";

const { connectAsync } = useConnect();
const connectWallet = async (connector: Connector) => {
    await connectAsync({ connector });
}
```

I'm testing with 
```
"@starknet-react/chains": "^3.0.0-beta.1",
"@starknet-react/core": "^3.0.0-beta.1",
"starknetkit": "^2.2.15",
"starknet": "^6.11.0",
```

**Comment by fracek** [comment] 2024-07-15 10:12
Thank you for the report! I will check what's going on and fix it.

**Comment by fracek** [comment] 2024-07-17 11:45
Hey @jrmncos if you are able to reproduce and can open a PR with a fix I'm happy to review it. Notice this is with the code in the `develop` branch.

**Comment by kseikyo** [comment] 2024-08-08 16:18
Is someone working on it? I'm currently debugging this issue, might send a patch PR later if I figure what's going on.

**Comment by fracek** [comment] 2024-08-10 11:40
I couldn't reproduce the issue. If you can and can submit a fix I'll be happy to review it!

**Comment by kseikyo** [comment] 2024-08-12 12:46
> I couldn't reproduce the issue. If you can and can submit a fix I'll be happy to review it!

I got the issue in my work project and this sandbox [here](https://stackblitz.com/edit/stackblitz-starters-uzoe6u?file=components%2Fconnect.tsx) for reference. I'm still investigating the issue, but so far I understand that the address is set when connected, but then reverts back to an empty string, while the connector is always undefined.

Tested with the following wallet versions:
Argent X: v5.17.8
Braavos: v3.69.2

**Comment by fracek** [comment] 2024-08-12 21:14
> > I couldn't reproduce the issue. If you can and can submit a fix I'll be happy to review it!
> 
> I got the issue in my work project and this sandbox [here](https://stackblitz.com/edit/stackblitz-starters-uzoe6u?file=components%2Fconnect.tsx) for reference. I'm still investigating the issue, but so far I understand that the address is set when connected, but then reverts back to an empty string, while the connector is always undefined.
> 
> Tested with the following wallet versions: Argent X: v5.17.8 Braavos: v3.69.2
> 
> Chromium Engine Version 127.0.6533.100

That's super helpful thank you!

**Comment by NGUYENDANGVU-coder** [comment] 2024-08-14 08:35
I'm currently debugging this issue. Can anyone help me?

**Comment by NGUYENDANGVU-coder** [comment] 2024-08-15 03:59
hey @fracek can you help me?

**Comment by jaipaljadeja** [comment] 2024-08-15 08:49
Hey @irisdv @kseikyo , this issue has been fixed in the latest beta release. Please update the `starknet-react` and `starknet` packages to the latest versions. Here's the updated [sandbox](https://stackblitz.com/edit/stackblitz-starters-bfnp6u) if it helps.

Also thank you @NGUYENDANGVU-coder  and @jrmncos  for offering to help with this issue. it's already been resolved now, so no further action is needed. : )

**Closed by jaipaljadeja** 2024-08-15 08:49 UTC
Labels: bug
