### ISSUE TITLE
Update `useAccount` hook to poll wallets in parallel

### ISSUE THREAD

**Issue by fracek** [apibara/starknet-react#482] opened 2024-08-21 17:10 UTC
The current implementation of `useAccount` iterates through all connectors to determine which one to connect to. This can be slow since some wallets take up to 500ms to answer the call.

The idea is to refactor [this piece of code](https://github.com/apibara/starknet-react/blob/main/packages/core/src/hooks/use-account.ts#L66-L101) to poll the connectors in parallel.

Notice the following constraints:

* `connector.request("wallet_getPermissions")` is called only if `connector.available()`
* `connector.request("wallet_getAccounts")` is called only if the connector has the right permissions.

**Comment by Iwueseiter** [comment] 2024-08-21 17:11
Hi

**Comment by kateberryd** [comment] 2024-08-21 17:11
Hi

**Comment by martinvibes** [comment] 2024-08-21 18:56
hello @fracek would love to work on this as it is my first issue here

**Comment by Blumebee** [comment] 2024-08-21 19:55
Hi @Iwueseiter @martinvibes @kateberryd, all applications must go through the ODHack hackathon page. All information are in the main telegram group or here: https://app.onlydust.com/hackathons/odhack-70 

Maintainers will be reviewing applications via the platform, not through the comments. Thanks for understanding and respecting this way!

**Comment by Iwueseiter** [comment] 2024-08-21 19:59
> Hi @Iwueseiter @martinvibes @kateberryd, all applications must go through the ODHack hackathon page. All information are in the main telegram group or here: https://app.onlydust.com/hackathons/odhack-70
> 
> Maintainers will be reviewing applications via the platform, not through the comments. Thanks for understanding and respecting this way!

For this particular project, there’s no provision to apply directly from onlydust.

**Comment by Blumebee** [comment] 2024-08-21 20:10
> > Hi @Iwueseiter @martinvibes @kateberryd, all applications must go through the ODHack hackathon page. All information are in the main telegram group or here: https://app.onlydust.com/hackathons/odhack-70
> > Maintainers will be reviewing applications via the platform, not through the comments. Thanks for understanding and respecting this way!
> 
> For this particular project, there’s no provision to apply directly from onlydust.

Sorry I didn't understand what you meant? It's an issue that is part of the ODHack so all applications will need to be via OnlyDust for it :)

**Comment by ShantelPeters** [comment] 2024-08-21 22:46
Hi @fracek can I be assigned to this issue 
This would be my first time contributing to this ecosystem

**Comment by MullerTheScientist** [comment] 2024-08-21 23:42
Hello @fracek  I want to address this issue

**Comment by BernalHQ** [comment] 2024-08-22 07:38
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
Hi, my name is Bernal. I currently work as a software developer in Costa Rica. I’m an enthusiast of Web3 technology, and I would love to contribute to this project.

### How I plan on tackling this issue

The first step is to understand the project and how it works. Once I have a good understanding of it, I’ll investigate the connectors in parallel, then think about an optimal solution for the refactoring. After that, I’ll implement the solution and run some tests to the refactored code.

**Comment by MatiasAchucarro** [comment] 2024-08-22 07:44
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
I am a passionate and results-driven web developer, currently deepening my knowledge in web3 technologies, Cairo, and open-source development through Dojo Coding. My skill set includes expertise in JavaScript, React, HTML, CSS, C# with .NET Entity Framework, and more. I also have experience with tools like Git, GitHub, SQL Server, and Postman. My focus has been on building solid web applications, from task lists to full-fledged CRUD systems, with front-end, back-end, and database integration.

This will be my first contribution to the open-source ecosystem, and I am excited to learn and collaborate on innovative projects, particularly those involving Cairo.

### How I plan on tackling this issue
To improve efficiency when probing connectors, you can perform the requests in parallel rather than sequentially. First, filter the available connectors. Then, create a function that checks permissions and retrieves accounts only if the connector has the appropriate permissions. Use Promise.all to execute these functions simultaneously and wait for all promises to resolve. Filter the results to keep only those connectors with available accounts and return the first valid one. This approach reduces the total wait time by handling requests in parallel.

**Comment by Iwueseiter** [comment] 2024-08-22 07:57
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
Hi @fracek can I work on this?
I'm a frontend and smart contract developer. with this experience, I'd tackle the issue as expected.
this will be done between 3 to 4 working days.

### How I plan on tackling this issue

Here is a brief approach to tackling the issue:
I'd check Availability in Parallel by Iterate over all connectors and check their availability using connector.available(), by doing this unavailable connectors will be filtered out
Request Permissions in Parallel: For each available connector, request "wallet_getPermissions" concurrently. Filter connectors that have the required permissions.
Request Accounts in Parallel, connectors with the correct permissions, request "wallet_getAccounts" concurrently. Collect and return the results.
I'll create a custom React hook called useAccount that performs these operations and returns the accounts retrieved from the connectors.

**Comment by Ugo-X** [comment] 2024-08-22 08:10
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, and Solidity. My journey with OnlyDust hackathons began at Edition 1, and I've since made 47 contributions across 11 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure.
I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges.
As we surf through Edition 7, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.


### How I plan on tackling this issue

I will approach the issue of refactoring the `useAccount` hook to poll connectors in parallel, improving performance while maintaining the existing constraints, as follows:

1. **Analyze the current implementation**:
   a. I will review the existing `useAccount` hook to understand its current logic and flow.
   b. I will identify the parts of the code that can be parallelized and those that need to remain sequential.

2. **Implement parallel polling of connectors**:
   a. I will use `Promise.all` to create an array of promises, each representing a connector check.
   b. For each connector, I will create an async function that:
      - Checks `connector.available()`.
      - If available, calls `connector.request("wallet_getPermissions")`.
      - If permissions are correct, calls `connector.request("wallet_getAccounts")`.
   c. I will ensure that these checks maintain the existing constraints and order of operations.

3. **Optimize error handling and timeouts**:
   a. I will implement proper error handling for each connector check.
   b. I will add a timeout mechanism to prevent long-running connector checks from blocking the entire process.

4. **Refactor the `useAccount` hook**:
   a. I will modify the hook to use the new parallel polling mechanism.
   b. I will ensure that the hook still returns the first valid account found.
   c. I will maintain any existing state management and side effects within the hook.

5. **Implement caching mechanism**:
   a. I will add a caching layer to store the results of connector checks.
   b. This cache will help prevent unnecessary repeated checks in subsequent renders.

6. **Update related components and hooks**:
   a. I will identify and update any components or hooks that depend on `useAccount`.
   b. I will ensure that these updates maintain backwards compatibility where possible.

7. **Performance testing**:
   a. I will conduct thorough performance tests to measure the improvement in connection times.
   b. I will use various scenarios, including different numbers of connectors and network conditions.

8. **Documentation and code comments**:
   a. I will update the documentation for the `useAccount` hook to reflect the new parallel implementation.
   b. I will add clear code comments explaining the parallel polling logic and constraints.

9. **Create comprehensive test suite**:
   a. I will write unit tests for the refactored `useAccount` hook.
   b. I will create integration tests to ensure proper interaction with actual connectors.
   c. I will include edge case tests, such as all connectors failing or timing out.

By implementing this solution, I aim to significantly reduce the time taken to determine the appropriate connector while maintaining the existing constraints and functionality of the `useAccount` hook. This parallel approach should provide a noticeable performance improvement, especially in scenarios with multiple slow-responding connectors.

**Comment by od-hunter** [comment] 2024-08-22 10:03
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
I am a blockchain developer with experience in html, css, react, JavaScript, typescript, solidity and Cairo.

### How I plan on tackling this issue
To solve this issue, I'd:
1. check the availability of all connectors simultaneously, request permissions and accounts in parallel for those connectors that are available and have the right permissions.
2. Next, I'll implement Parallel Execution(use Promise.all or similar techniques to handle parallel requests efficiently.

Please assign me I'm ready to work.

**Comment by Benjtalkshow** [comment] 2024-08-22 10:20
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
Hi @fracek

I'm available to work on refactoring the `useAccount` implementation to improve its performance. My name is Benjamin, and I have extensive experience in optimizing code and working with asynchronous operations. My background includes enhancing the efficiency of existing implementations and ensuring smooth user experiences.

### Understanding the Issue
The current implementation of `useAccount` iterates through all connectors sequentially to determine which one to connect to. This approach can be slow because some wallets may take up to 500ms to respond. The goal is to refactor this code to poll the connectors in parallel, which should improve the responsiveness of the connection process.


### How I plan on tackling this issue
#### Refactor `useAccount` for Parallel Polling
- **Check Connector Availability**: First, I will verify if each connector is available using the `connector.available()` method. This step ensures that we only attempt to interact with connectors that are actually available.
- **Parallel Polling**: I will modify the implementation to poll all available connectors in parallel rather than sequentially. This approach will significantly reduce the total time required to determine the appropriate connector.

#### Implement Permissions and Accounts Check
- **Permissions Check**: For each connector, I will check if the necessary permissions are granted by calling `connector.request("wallet_getPermissions")`. This step will be executed only if the connector is available.
- **Accounts Retrieval**: Once permissions are confirmed, I will call `connector.request("wallet_getAccounts")` to retrieve the accounts associated with the connector. This call will be made only if the connector has the required permissions.

#### Asynchronous Operations
- **Promise Handling**: I will handle the parallel polling using promises to ensure that all connectors are processed concurrently. This will involve using `Promise.all` or similar techniques to manage the asynchronous operations.

### Testing
- **Performance Testing**: I will conduct performance tests to compare the new parallel polling implementation against the old sequential approach, measuring improvements in connection speed and responsiveness.
- **Functional Testing**: I will ensure that all connectors are correctly identified and that the permissions and accounts retrieval process works as expected for each connector.

**Comment by LazarusAA** [comment] 2024-08-22 10:32
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
I'm a blockchain developer with experience in rust, JavaScript, typescript, solidity and Cairo. This is my first time contributing to Starknet-React and Id love to work on this issue.

### How I plan on tackling this issue
- Check the availability of all connectors simultaneously
- Request accounts in parallel for connectors with the right permissions
- Implement Parallel Execution
- Test that everything works as intended

Thank you for your consideration.

**Comment by LukePereyra** [comment] 2024-08-22 12:27
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
hey team I'm a Frontend developer. I have experience in React, and this could be one of my first issues in Onlydust

### How I plan on tackling this issue
I have experience executing request in parallel with JS. I will handle all the connection in an async way, and then decide which one to use trying to avoid the 500ms delay

**Comment by bitfalt** [comment] 2024-08-22 13:15
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
Hii, my name is Daniel and I'm a software and web3 developer. I've been learning about parallelization and TypeScript lately given my University courses and degree (Computer Science). I'm also member of the Dojo Coding community.

### How I plan on tackling this issue
The way I would the issue is in the following way:
- Implement threads to the TypeScript code, this involves refactoring the code accordingly (create more functions, modify existing function).
- Given the parallelizatio needs, I will split the connectors in chunks to assign it to the proper threads.
- Make sure to follow the constraints given so that the threads will behave properly.
- I will ask the maintainers if any questions or errors come up during my implementation.

**Comment by ScottyDavies** [comment] 2024-08-22 13:19
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
As an experienced frontend developer, I can leverage my expertise in asynchronous programming, Web3 integrations, code optimization, and testing to refactor the useAccount function and address its performance issues

### How I plan on tackling this issue
I would approach this issue with following steps
Analyze the Existing Implementation: First, I would carefully examine the current implementation of the useAccount function to understand its structure, identify the performance bottlenecks, and determine the areas that can be optimized.
Parallelize the Connector Checks: The key to addressing the performance issues is to refactor the function to poll the connectors in parallel, instead of iterating through them sequentially. I would leverage asynchronous programming techniques, such as Promise.all() or async/await, to execute the connector.request() calls concurrently.
Optimize Conditional Checks: To adhere to the given constraints, I would ensure that the connector.available() and permissions checks are performed before making the subsequent API calls. This will help avoid unnecessary requests and improve the overall efficiency of the function.
Implement Error Handling and Fallbacks: I would also add robust error handling and fallback mechanisms to the refactored function. This will ensure that the function can gracefully handle failures or timeouts from the wallet providers, providing a better user experience.
Write Comprehensive Tests: To ensure the correctness and reliability of the refactored useAccount function, I would create a comprehensive test suite using a framework like Jest. This will help catch regressions and verify the expected behavior of the function under various conditions.
Measure and Optimize Performance: After implementing the refactored function, I would measure its performance and identify any remaining bottlenecks. I would then further optimize the code, if necessary, to ensure that the function meets the desired performance goals.

**Comment by ShantelPeters** [comment] 2024-08-22 13:24
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
I have a background in frontend and blockchain development, including integrating wallet functionality and optimizing interactions with smart contracts. My experience with asynchronous programming and performance optimization in web applications will help efficiently refactor the `useAccount` implementation to poll connectors in parallel, improving response times and overall user experience.

### How I plan on tackling this issue
To improve the `useAccount` implementation, I would refactor the code to utilize asynchronous parallel processing. Specifically, I would:

1. **Check Connector Availability**: Filter connectors to only those that are available.
2. **Parallel Requests**: Use `Promise.all` to execute `connector.request("wallet_getPermissions")` for all available connectors simultaneously.
3. **Filter by Permissions**: After receiving responses, filter connectors with the required permissions.
4. **Request Accounts**: Again, use `Promise.all` to request accounts from connectors that have the correct permissions.

**Comment by bhavyagosai** [comment] 2024-08-22 14:48
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
Hey, I am Bhavya, a seasoned frontend engineer with two years of professional experience. I have been working with react and typescript and have extensive experience with them!

### How I plan on tackling this issue
I can see that the problem we face here is coming up because of the use of a `for loop` with async queries inside it, which can slow down the function.

To tackle this, what I would do is:

- first of all filter connectors to only include those that are available, minimizing unnecessary calls. This is done using `connectors.filter((connector) => connector.available())`
- Now each connectors's polling operation should be handled in parallel, for that either we can use `promise.all` or `promise.any`
  - in this case, we need to proceed with the first successful result, regardless of how many other promises fail and ignore all rejected promised unless all of them fail. Basically need to return the first fulfilled/resolved promise.
  - Therefore, `promise.any` should be a better option to use here instead of `promise.all` as that would wait for all promises to either resolve or reject, and would essentially resolve only when all promises fulfilled.
  - If all promises reject, the catch block would handle the situation and throw an `AggregateError`.
  - instead of returning `null` for unsuccessful attempts, we would throw an error to immediately reject that promise, ensuring the `Promise.any` can ignore it and move on.
- `wallet_getPermissions` call is made only for the connectors which are available and skip the connectors which do not have the required permissions (in our case `ACCOUNTS`)
- after these checks are passed for a wallet to be connected and having required permissions, we request accounts from the wallet and check if the account matches the connected account
- The matching account is thus used to update the state.

This approach is more performant and elegant as it avoids unnecessary waiting when you only need one and first successful result.

**Comment by Luluameh** [comment] 2024-08-22 16:55
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
I am a frontend developer with extensive experience in React.js ,utilizing TypeScript to build dynamic and responsive user interfaces. My background in these technologies allows me to create seamless and efficient web applications, focusing on delivering a user-friendly experience. By combining my technical skills with a strong understanding of modern development practices, I am well-equipped to contribute to any project, ensuring that the final product is both high-performing and intuitive for end-users.

### How I plan on tackling this issue
To effectively approach a problem, I would follow a systematic process:

Understand the Problem:

Begin by fully understanding the problem statement. I would identify the key requirements, constraints, and goals to ensure I’m addressing the right issue.
Research and Analysis:

Conduct thorough research to explore existing solutions or similar problems. Analyze different approaches to determine the most effective solution that aligns with the project’s needs.
Break Down the Problem:

Decompose the problem into smaller, manageable tasks. This helps in tackling each aspect individually and ensures that no critical details are overlooked.
Plan and Strategize:

Develop a detailed plan of action, including the technologies, tools, and methods that will be used. I would prioritize tasks based on their importance and dependencies.
Implement the Solution:

Begin coding or applying the solution step by step, adhering to best practices and coding standards. I would continuously test the solution during implementation to catch and resolve issues early.

**Comment by JoelVR17** [comment] 2024-08-22 17:12
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
I'm a Full Stack Web Developer with a solid background in front-end and back-end development. So it will be a pleasure to contribute for the first time to this great project. *_I am a member of the Dojo Coding community._*

### How I plan on tackling this issue
1. **Understand the Current Workflow:**
   - The current implementation sequentially iterates through each connector, which can be slow because some wallets may take up to 500ms to respond.
   - The goal is to refactor this to poll connectors in parallel while adhering to the constraints: calling `connector.request("wallet_getPermissions")` only if the connector is available and `connector.request("wallet_getAccounts")` only if the correct permissions are granted.

2. **Refactor the Code to Poll Connectors in Parallel:**
   - I would utilize `Promise.all` to poll all connectors simultaneously, improving the speed of the connection process.
   - Each connector's availability will be checked in parallel, and then the permissions and accounts will be requested based on availability and permissions.

3. **Implement Parallel Processing:**
   - I will modify the `refreshState` function to process each connector in parallel using `Promise.all`. This will involve creating a promise for each connector that checks availability, permissions, and accounts in sequence but allows all connectors to be processed simultaneously.
   - The first connector that returns a valid account matching the `connectedAccount` will update the state and stop further processing.

4. **Error Handling:**
   - I will ensure that the refactored code handles any potential errors gracefully, allowing other connectors to continue processing even if one fails.
   - The refactoring will include try-catch blocks within each promise to capture errors without disrupting the overall flow.

5. **Testing and Verification:**
   - After refactoring, I will thoroughly test the function to ensure it handles all scenarios correctly, including:
     - Multiple connectors responding at different times.
     - Connectors failing to respond or throwing errors.
     - The state being correctly updated with the first valid connector.
   - Performance tests will be conducted to compare the speed of the refactored code with the original sequential implementation, ensuring a noticeable improvement in response time.

### Refactored Code Implementation:

```typescript
import type { Address } from "@starknet-react/chains";
import { useCallback, useEffect, useState } from "react";
import type { AccountInterface } from "starknet";

import type { Connector } from "../connectors";
import { useStarknetAccount } from "../context/account";

import { Permission } from "@starknet-io/types-js";
import { useConnect } from "./use-connect";

/** Account connection status. */
export type AccountStatus =
  | "connected"
  | "disconnected"
  | "connecting"
  | "reconnecting";

/** Value returned from `useAccount`. */
export type UseAccountResult = {
  account?: AccountInterface;
  address?: Address;
  connector?: Connector;
  chainId?: bigint;
  isConnecting?: boolean;
  isReconnecting?: boolean;
  isConnected?: boolean;
  isDisconnected?: boolean;
  status: AccountStatus;
};

/** Hook for accessing the account and its connection status. */
export function useAccount(): UseAccountResult {
  const { account: connectedAccount } = useStarknetAccount();
  const { connectors } = useConnect();
  const [state, setState] = useState<UseAccountResult>({
    status: "disconnected",
  });

  const refreshState = useCallback(async () => {
    if (!connectedAccount) {
      return setState({
        status: "disconnected",
        isDisconnected: true,
        isConnected: false,
        isConnecting: false,
        isReconnecting: false,
      });
    }

    const connectorPromises = connectors.map(async (connector) => {
      if (!connector.available()) return null;

      try {
        const permissions: Permission[] = await connector.request({
          type: "wallet_getPermissions",
        });

        if (!permissions.includes(Permission.ACCOUNTS)) return null;

        const connAccount = await connector.request({
          type: "wallet_requestAccounts",
          params: { silent_mode: true },
        });

        if (connAccount?.[0] === connectedAccount.address) {
          return {
            connector,
            chainId: await connector.chainId(),
          };
        }
      } catch {
        return null;
      }
      return null;
    });

    const results = await Promise.all(connectorPromises);

    const validResult = results.find((result) => result !== null);

    if (validResult) {
      setState({
        connector: validResult.connector,
        chainId: validResult.chainId,
        account: connectedAccount,
        address: connectedAccount.address as Address,
        status: "connected",
        isConnected: true,
        isConnecting: false,
        isDisconnected: false,
        isReconnecting: false,
      });
    } else {
      setState({
        connector: undefined,
        chainId: undefined,
        account: connectedAccount,
        address: connectedAccount.address as Address,
        status: "connected",
        isConnected: true,
        isConnecting: false,
        isDisconnected: false,
        isReconnecting: false,
      });
    }
  }, [connectedAccount, connectors]);

  useEffect(() => {
    refreshState();
  }, [refreshState]);

  return state;
}

**Comment by DIWAKARKASHYAP** [comment] 2024-08-26 16:52
i want to work on this issue

**Closed** 2024-09-01 10:44 UTC
Labels: ODHack7, feature-request
