### ISSUE TITLE
Issue when both ArgentX and Braavos wallets enabled

### ISSUE THREAD

**Issue by Pet3ris** [apibara/starknet-react#97] opened 2022-05-03 14:13 UTC
Running into this issue on Brave where if both ArgentX and Braavos wallets are enabled, I get the following error:

![Screen Shot 2022-05-03 at 3 12 24 PM](https://user-images.githubusercontent.com/224585/166470013-70a2b986-62f1-4e37-af35-a22f82b64889.png)

**Comment by fracek** [comment] 2022-05-03 14:20
Related to #77. Need to fix this ASAP.

**Comment by avimak** [comment] 2022-05-04 14:23
@fracek the root cause actually sits in argent's extension, see [here](https://github.com/argentlabs/argent-x/blob/develop/packages/extension/src/inpage/index.ts#L161)

**Comment by fracek** [comment] 2022-05-04 15:48
Where should we track this issue? /cc @janek26

**Comment by Pet3ris** [comment] 2022-06-01 08:07
This is a good tweet from Vitalik of the benefit of testing with multiple wallets: https://twitter.com/VitalikButerin/status/1531771109602799617.

**Comment by fracek** [comment] 2022-06-02 14:57
#109 fixes this. Let's get it merged.

**Comment by fracek** [comment] 2022-06-04 20:21
This is now fixed.

**Closed by fracek** 2022-06-04 20:21 UTC
Labels: bug
